Repository My-Epitech-Organisation/Raytracer, pull requests merged in 2025-04, with the labels that each got.

#1 🚀 Initial Project Setup
  .clang-format
  .github/ISSUE_TEMPLATE/project_issue_template.md
  .github/workflows/ci.yml
  LICENSE
  docs/ARCHITECTURE.md
  docs/COMMIT_CONVENTION.md
  docs/CONTRIBUTING.md
  docs/ISSUE_TEMPLATE_USAGE.md
  docs/pdf/B-OOP-400_raytracer.pdf
  docs/pdf/B-OOP-400_raytracer_bootstrap.pdf
Labels: type:documentation, type:feature

#6 feat(github issues): add issue templates for bug reports, feature requests, improvements, and tasks
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/improvement.yml
  .github/ISSUE_TEMPLATE/project_issue_template.md
  .github/ISSUE_TEMPLATE/task.yml
Labels: type:chore, priority:high

#8 feat: update issue templates to use 'description' field for clarity
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/improvement.yml
  .github/ISSUE_TEMPLATE/task.yml
Labels: type:chore

#10 Initial setup
  .github/ISSUE_TEMPLATE/task.yml
  docs/ISSUE_TEMPLATE_USAGE.md
Labels: type:documentation, type:chore

#33 12 gitignore clangformat
  .clang-format
  .gitignore
Labels: type:chore

#34 Initial setup
  .gitignore
  CMakeLists.txt
  Makefile
  cmake/FetchGoogleTest.cmake
  include/Error.hpp
  include/IDisplay.hpp
  include/ILight.hpp
  include/IPrimitive.hpp
  plugins/lights/sample_point/CMakeLists.txt
  plugins/lights/sample_point/PointLightPlugin.cpp
  plugins/primitives/sample_sphere/CMakeLists.txt
  plugins/primitives/sample_sphere/SpherePlugin.cpp
  scenes/demo_plane.cfg
  scenes/demo_sphere.cfg
  src/CMakeLists.txt
  src/core/Color.cpp
  src/core/Color.hpp
  src/core/Mat4.cpp
  src/core/Mat4.hpp
  src/core/Ray.cpp
  src/core/Ray.hpp
  src/core/Transform.cpp
  src/core/Transform.hpp
  src/core/Vec3.cpp
  src/core/Vec3.hpp
  src/display/PPMDisplay.cpp
  src/display/PPMDisplay.hpp
  src/display/SFMLDisplay.cpp
  src/display/SFMLDisplay.hpp
  src/main.cpp
  src/scene/Camera.cpp
  src/scene/Camera.hpp
  src/scene/Scene.cpp
  src/scene/Scene.hpp
  src/scene/SceneBuilder.cpp
  src/scene/SceneBuilder.hpp
  src/scene/lights/AmbientLight.hpp
  src/scene/lights/DirectionalLight.cpp
  src/scene/lights/DirectionalLight.hpp
  src/scene/primitives/Cylinder.cpp
  src/scene/primitives/Cylinder.hpp
  src/scene/primitives/Plane.cpp
  src/scene/primitives/Plane.hpp
  src/scene/primitives/Sphere.cpp
  src/scene/primitives/Sphere.hpp
  tests/CMakeLists.txt
  tests/test_parser.cpp
  tests/test_ray.cpp
  tests/test_vec3.cpp
Labels: component:core

#37 feat(Ray): implement Ray class with constructors, destructors, and transformation methods
  src/core/Ray.cpp
  src/core/Ray.hpp
  tests/CMakeLists.txt
  tests/test_ray.cpp
Labels: type:TDD, component:core

#38 Implement vector3d class
  Makefile
  src/core/Transform.cpp
  src/core/Transform.hpp
  src/core/Vector3D.cpp
  src/core/Vector3D.hpp
  src/main.cpp
  tests/test_Transform.cpp
  tests/test_Vector3D.cpp
  tests/test_vec3.cpp
Labels: component:core
